version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/EndpointManagerLauncher
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /src/LocalAgent
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/LocalAgent
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/common.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/common
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/devhostAgent.restorationjob.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /src/devhostagent.restorationjob
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/devhostagent.restorationjob
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /src/devhostagent
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/devhostagent
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/dsc.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/dsc
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/endpointmanager.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/endpointmanager
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/library.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/library
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/routingmanager.tests
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /src/routingmanager
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/routingmanager
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0

  - package-ecosystem: nuget
    directory: /src/testhelpers
    schedule:
      interval: monthly
    # enable only security updates
    open-pull-requests-limit: 0
