#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/sdk:8.0.101 AS build

RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

ARG Configuration=Release
ARG TelemetryType=TELEMETRY_DEVELOPMENT
ARG MindaroBuildNumber=0.0

ARG DEVDIV_PKGS_USERNAME
ARG DEVDIV_PKGS_PASSWORD

ARG VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{'endpointCredentials': [{'endpoint':'https://devdiv.pkgs.visualstudio.com/_packaging/Mindaro/nuget/v3/index.json', 'username':'${DEVDIV_PKGS_USERNAME}', 'password':'${DEVDIV_PKGS_PASSWORD}'}]}"

WORKDIR /src/localagent
COPY /src/nuget.config .
COPY /src/nuget.config /src/library/
COPY /src/localagent/localagent.csproj .
COPY /src/common/common.csproj /src/common/
COPY /src/library/library.csproj /src/library/
COPY /deployment/settings/services/imagetag.setting /deployment/settings/services/imagetag.setting
RUN dotnet restore
COPY /src/localagent/ /src/localagent/
COPY /src/common/ /src/common/
copy /src/library/ /src/library/
COPY /build/ /build/
ENV TelemetryType=${TelemetryType}
ENV MINDARO_BUILD_NUMBER=${MindaroBuildNumber}

RUN dotnet publish -c ${Configuration} -o /src/publish

# Final container
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine3.17 as final

# Setup common tools
COPY /build/setup-alpine-tools.sh .
RUN chmod +x ./setup-alpine-tools.sh \
    && ./setup-alpine-tools.sh \
    && rm -f ./setup-alpine-tools.sh

WORKDIR /src/localagent
COPY --from=build /src/publish /src/localagent
ENTRYPOINT ["dotnet", "/src/localagent/Microsoft.BridgeToKubernetes.LocalAgent.dll"]