apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-webapp
  namespace: mi-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-webapp
  template:
    metadata:
      labels:
        app: mi-webapp
        # Label for pod identity
        aadpodidbinding: mi-test
    spec:
      containers:
        - image: azdspublic/mi-webapp
          imagePullPolicy: IfNotPresent
          name: mi-webapp
          env:
          # the below environment variable values come from the below sub and rg:
          # Sub: Mindaro Testing (c2e0f009-a61a-4578-8a6d-5715ee782648)
          # RG: testing-scenario
          # Storage account name: mitestsa
          # Managed identity name: mi-test
          - name: STORAGE_ACCOUNT_NAME
            value: "mitestsa"
          - name: STORAGE_CONTAINER_NAME
            value: "mitestsa-container"
          - name: MI_CLIENT_ID
            value: "b24d4637-3453-4f6f-8187-228a5442a675"
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mi-webapp-service
  namespace: mi-webapp
spec:
  selector:
    app: mi-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
# AzureIdentity resource for pod identity 
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: mi-test
spec:
  type: 0
  resourceID: "/subscriptions/c2e0f009-a61a-4578-8a6d-5715ee782648/resourcegroups/MC_testing-scenario_testing-scenarios_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-test"
  clientID: "b24d4637-3453-4f6f-8187-228a5442a675"

---
# AzureIdentityBinding resource for pod identity 
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: mi-test-binding
spec:
  azureIdentity: mi-test
  selector: mi-test