apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: connect-sql-db
  name: connect-sql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-sql-db
  template:
    metadata:
      labels:
        app: connect-sql-db
    spec:
      containers:
      - image: docker.io/ansoedal/connect-sql-db:latest
        imagePullPolicy: Always
        name: connect-sql-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env: 
        - name: DB_HOST
          value: "server-bridgetest123.database.windows.net"
        - name: DB_NAME
          value: "database-bridgetest123"
        - name: DB_PASSWORD
          value: "PLACEHOLDER"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: connect-sql-db
  labels:
    app: connect-sql-db
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:    
    app: connect-sql-db