//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.BridgeToKubernetes.Exe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.BridgeToKubernetes.Exe.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Once your cluster environment is replicated, all processes on your machine will be able to access it.
        /// </summary>
        internal static string AdminPermissionsDisclaimer {
            get {
                return ResourceManager.GetString("AdminPermissionsDisclaimer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string AdminPermissionsPrompt {
            get {
                return ResourceManager.GetString("AdminPermissionsPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debugging with {0} requires administrator permissions to:.
        /// </summary>
        internal static string AdminPermissionsRequiredFormat {
            get {
                return ResourceManager.GetString("AdminPermissionsRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect operation failed..
        /// </summary>
        internal static string Error_ConnectOperationFailed {
            get {
                return ResourceManager.GetString("Error_ConnectOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get process &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Error_FailedToGetProcess {
            get {
                return ResourceManager.GetString("Error_FailedToGetProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; incorrect: {1}.
        /// </summary>
        internal static string Error_IncorrectOption {
            get {
                return ResourceManager.GetString("Error_IncorrectOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid value provided for &apos;{0}&apos;.
        /// </summary>
        internal static string Error_InvalidConfigurationValue {
            get {
                return ResourceManager.GetString("Error_InvalidConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must specify a valid port number.
        /// </summary>
        internal static string Error_InvalidPort {
            get {
                return ResourceManager.GetString("Error_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} value.
        /// </summary>
        internal static string Error_InvalidElevationRequestsValue {
            get {
                return ResourceManager.GetString("Error_InvalidElevationRequestsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        internal static string Error_OperationCanceled {
            get {
                return ResourceManager.GetString("Error_OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify exactly one of &apos;{0}&apos; to identify the container to connect to..
        /// </summary>
        internal static string Error_SpecifyOneContainerIdentifier {
            get {
                return ResourceManager.GetString("Error_SpecifyOneContainerIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get routing manager deployment status: &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToGetRoutingManagerDeploymentStatusFormat {
            get {
                return ResourceManager.GetString("FailedToGetRoutingManagerDeploymentStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get routing manager deployment status - ran out of time : &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToGetRoutingManagerDeploymentStatusRanOutOfTimeFormat {
            get {
                return ResourceManager.GetString("FailedToGetRoutingManagerDeploymentStatusRanOutOfTimeFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to perform action on the cluster using the current kubeconfig. You may need to log in by running a kubectl command.
        /// </summary>
        internal static string FailedToPerformActionLoginNeeded {
            get {
                return ResourceManager.GetString("FailedToPerformActionLoginNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working isolated is currently not supported by Bridge to Kubernetes when working with Dapr. Please retry without isolation..
        /// </summary>
        internal static string IsolationIsNotAvailableWithDaprError {
            get {
                return ResourceManager.GetString("IsolationIsNotAvailableWithDaprError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established..
        /// </summary>
        internal static string Progress_ConnectionEstablished {
            get {
                return ResourceManager.GetString("Progress_ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment started..
        /// </summary>
        internal static string Progress_EnvironmentStarted {
            get {
                return ResourceManager.GetString("Progress_EnvironmentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run {0} in your existing console to also get connected..
        /// </summary>
        internal static string Progress_RunScriptToConnect {
            get {
                return ResourceManager.GetString("Progress_RunScriptToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping workload and cleaning up....
        /// </summary>
        internal static string Progress_StoppingWorkload {
            get {
                return ResourceManager.GetString("Progress_StoppingWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered stopping the session. Please confirm that your workload has been restored successfully..
        /// </summary>
        internal static string RemotingAPI_StopFailed {
            get {
                return ResourceManager.GetString("RemotingAPI_StopFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string Warning_Cancelling {
            get {
                return ResourceManager.GetString("Warning_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload change detected. Reconnecting....
        /// </summary>
        internal static string WorkloadChangeDetected {
            get {
                return ResourceManager.GetString("WorkloadChangeDetected", resourceCulture);
            }
        }
    }
}
