//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.BridgeToKubernetes.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.BridgeToKubernetes.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the following Client Request ID when contacting support: {0}.
        /// </summary>
        internal static string ClientRequestIdErrorMessageFormat {
            get {
                return ResourceManager.GetString("ClientRequestIdErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the following Correlation ID when contacting support: &apos;{0}&apos;. .
        /// </summary>
        internal static string CorrelationIdErrorMessageFormat {
            get {
                return ResourceManager.GetString("CorrelationIdErrorMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update your machine's hosts file to match your Kubernetes cluster environment.
        /// </summary>
        internal static string ElevationRequest_EditHostsFile {
            get {
                return ResourceManager.GetString("ElevationRequest_EditHostsFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop {0} to free port {1}
        /// </summary>
        internal static string ElevationRequest_FreePortRequestFormat {
            get {
                return ResourceManager.GetString("ElevationRequest_FreePortRequestFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see our active issues or file a bug report, please visit {0}..
        /// </summary>
        internal static string Error_BridgeReport {
            get {
                return ResourceManager.GetString("Error_BridgeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... An unexpected error has occurred..
        /// </summary>
        internal static string Error_OopsMessage {
            get {
                return ResourceManager.GetString("Error_OopsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For diagnostic information, see logs at &apos;{0}&apos;..
        /// </summary>
        internal static string Error_SeeLogFile {
            get {
                return ResourceManager.GetString("Error_SeeLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: &apos;{0}&apos;.
        /// </summary>
        internal static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Defaulting to reading environment variables from the container manifest....
        /// </summary>
        internal static string DefaultingToContainerSpecEnvironmentVariables {
            get {
                return ResourceManager.GetString("DefaultingToContainerSpecEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine the cluster details from the kubeconfig file &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDetermineClusterDetailsFromKubeConfig {
            get {
                return ResourceManager.GetString("FailedToDetermineClusterDetailsFromKubeConfig", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve environment variables from container &apos;{0}&apos;. If you are using a minimal base image, please switch to a base image that includes the env utility. If the code you are debugging does not rely on environment variables from the container, you can ignore this error..
        /// </summary>
        internal static string FailedToGetTheContainerEnvironmentMinimalImageFormat {
            get {
                return ResourceManager.GetString("FailedToGetTheContainerEnvironmentMinimalImageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get the environment for container &apos;{0}&apos;. Error: &apos;{1}&apos;.
        /// </summary>
        internal static string FailedToGetTheContainerEnvironmentFormat {
            get {
                return ResourceManager.GetString("FailedToGetTheContainerEnvironmentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load current context from kubeconfig. Please confirm that your kubeconfig is valid..
        /// </summary>
        internal static string FailedToLoadKubeConfigContext {
            get {
                return ResourceManager.GetString("FailedToLoadKubeConfigContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load current kubeconfig. This could be due to a typo in your kubeconfig or to an unsupported configuration. For more information, please see {0}..
        /// </summary>
        internal static string FailedToLoadKubeConfigFormat {
            get {
                return ResourceManager.GetString("FailedToLoadKubeConfigFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encountered permissions error. To see which permissions you need to run {0}, visit {1}. Error: {2}.
        /// </summary>
        internal static string IncludeRBACInformationFormat {
            get {
                return ResourceManager.GetString("IncludeRBACInformationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value provided for isolateAs header: &apos;{0}&apos;. The value cannot contain spaces..
        /// </summary>
        internal static string InvalidRoutingValueWithSpaceFormat {
            get {
                return ResourceManager.GetString("InvalidRoutingValueWithSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value provided for isolateAs header: &apos;{0}&apos;. The value cannot contain upper case characters..
        /// </summary>
        internal static string InvalidRoutingValueWithUpperCaseFormat {
            get {
                return ResourceManager.GetString("InvalidRoutingValueWithUpperCaseFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid value provided for isolateAs header: &apos;{0}&apos;. The value may only contain alphanumeric characters..
        /// </summary>
        internal static string InvalidRoutingValue
        {
            get
            {
                return ResourceManager.GetString("InvalidRoutingValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred merging kubeconfig files. Please run &apos;KUBECONFIG={0}:{1} kubectl config view --flatten&apos; to manually merge the config files and try again..
        /// </summary>
        internal static string KubeConfigMergeFailedFormat {
            get {
                return ResourceManager.GetString("KubeConfigMergeFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred setting the kubeconfig context. Please run &apos;kubectl config set - context {0} --namespace={1}&apos; to set the context and try again..
        /// </summary>
        internal static string KubeConfigSetContextFailedFormat {
            get {
                return ResourceManager.GetString("KubeConfigSetContextFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current platform is not supported for kubectl..
        /// </summary>
        internal static string KubectlNotSupportedMessage {
            get {
                return ResourceManager.GetString("KubectlNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kubernetes cluster found. Please check your kubeconfig..
        /// </summary>
        internal static string NoKubernetesClusterFound {
            get {
                return ResourceManager.GetString("NoKubernetesClusterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the following Request ID when contacting support: {0}.
        /// </summary>
        internal static string RequestIdErrorMessageFormat {
            get {
                return ResourceManager.GetString("RequestIdErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Failed to delete pod &apos;{0}/{1}&apos;..
        /// </summary>
        internal static string RestoreFailedToDeletePodFormat {
            get {
                return ResourceManager.GetString("RestoreFailedToDeletePodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Failed to restore {0} &apos;{1}&apos; to original state..
        /// </summary>
        internal static string RestoreFailedToRestoreResourceFormat {
            get {
                return ResourceManager.GetString("RestoreFailedToRestoreResourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Failed to restore {0} &apos;{1}&apos; to original state with image &apos;{2}&apos;..
        /// </summary>
        internal static string RestoreFailedToRestoreResourceWithImageFormat {
            get {
                return ResourceManager.GetString("RestoreFailedToRestoreResourceWithImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Pod &apos;{0}&apos; deleted..
        /// </summary>
        internal static string RestorePodDeletedFormat {
            get {
                return ResourceManager.GetString("RestorePodDeletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Pod &apos;{0}&apos; restored to original state..
        /// </summary>
        internal static string RestorePodRestoredFormat {
            get {
                return ResourceManager.GetString("RestorePodRestoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Pod &apos;{0}&apos; restored to original state with image &apos;{1}&apos;..
        /// </summary>
        internal static string RestorePodRestoredWithImageFormat {
            get {
                return ResourceManager.GetString("RestorePodRestoredWithImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: Failed to restore pod &apos;{0}&apos; to original state with image &apos;{1}&apos;..
        /// </summary>
        internal static string RestorePodRestoreFailedWithImageFormat {
            get {
                return ResourceManager.GetString("RestorePodRestoreFailedWithImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: {0} &apos;{1}&apos; restored to original state..
        /// </summary>
        internal static string RestoreResourceRestoredFormat {
            get {
                return ResourceManager.GetString("RestoreResourceRestoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore: {0} &apos;{1}&apos; restored to original state with image &apos;{2}&apos;..
        /// </summary>
        internal static string RestoreResourceRestoredWithImageFormat {
            get {
                return ResourceManager.GetString("RestoreResourceRestoredWithImageFormat", resourceCulture);
            }
        }
    }
}
