name: Install Script Integration Test
on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Install Script 
        run: ./scripts/install.sh
      - name: Validate Command is Installed
        run: |
          if ! command -v /home/runner/.local/bin/bridgetokubernetes/dsc &> /dev/null
          then
              echo "B2K could not be found"
              exit 1
          fi
      - name: Validate B2k Command Runs
        run: /home/runner/.local/bin/bridgetokubernetes/dsc connect --help
    