name: Install Script Integration Test
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run Install Script
        shell: bash
        run: ./scripts/install.sh
      - name: Validate Command is Installed
        shell: bash
        run: |
          if command -v /home/runner/.local/bin/bridgetokubernetes/dsc &> /dev/null
          then
              echo "install_dir=/home/runner/.local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
          elif command -v /usr/local/bin/bridgetokubernetes/dsc &> /dev/null 
          then
            echo "install_dir=/usr/local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
          elif command -v /c/Users/runneradmin/.local/bin/bridgetokubernetes/dsc &> /dev/null
          then
            echo "install_dir=/c/Users/runneradmin/.local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
          else 
            echo "B2k CLI is not found"
            exit 1
          fi
      - name: Validate B2k Command Runs
        shell: bash
        run: ${{ env.install_dir }} connect --help
    