name: Install Script Integration Test
on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install git bash for windows
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          inlineScript: |
            winget install --id Git.Git -e --source winget
          azPSVersion: '3.1.0'
      - name: Run Install Script 
        run: ./scripts/install.sh
      - name: Validate Command is Installed
        run: |
          if command -v /home/runner/.local/bin/bridgetokubernetes/dsc &> /dev/null
          then
              echo "install_dir=/home/runner/.local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
          elif command -v /usr/local/bin/bridgetokubernetes/dsc &> /dev/null 
          then
            echo "install_dir=/usr/local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
          else 
            echo "B2k CLI is not found"
            exit 1
          fi
      - name: Validate B2k Command Runs
        run: ${{ env.install_dir }} connect --help
    